services:
  core-service:
    build:
      context: ./core-service
    image: silver-carnival/core-service:latest
    deploy:
      replicas: 2

  processing-service:
    build:
      context: ./processing-service
    image: silver-carnival/processing-service:latest
    deploy:
      replicas: 2

  import-service:
    build:
      context: ./import-service
    image: silver-carnival/import-service:latest
    ports:
      - "8083:8083"

  task-service:
    build:
      context: ./task-service
    image: silver-carnival/task-service:latest
    deploy:
      replicas: 2

  proxy:
    build:
      context: ./proxy
    image: silver-carnival/proxy:latest
    ports:
      - "8080:8080"
    depends_on:
      - core-service
      - processing-service
      - import-service
      - task-service
