events {}

http {
    server {
        listen 8080;

        location /core/ {
            proxy_pass http://core-service:8081/;
        }

        location /processing/ {
            proxy_pass http://processing-service:8082/;
        }

        location /import/ {
            proxy_pass http://import-service:8083/;
        }

        location /task/ {
            proxy_pass http://task-service:8084/;
        }
    }
}
